import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "./components/ui/sidebar";
import { AppSidebar } from "./components/layout/AppSideBar";

const GeistFont = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR" className={`${GeistFont.variable} h-full`}>
      <body
        className={`${GeistFont.variable} bg-background-page h-full antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1 m-6 max-w-7xl mx-auto w-full">
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
